name: planzapp
description: planzApp - FLUTTER version

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  #foursquare: ^0.1.0
  dotenv: ^4.0.1
  intl: ^0.17.0
  pretty_json: ^2.0.0
  expandable: ^5.0.1
#  mongo_dart: ^0.4.3
  uuid: ^3.0.6
  provider: ^5.0.0
  # http: ^0.13.0
  http_retry: ^0.2.0
  maps_launcher: ^2.0.0
  mailer: ^5.0.0
  flutter_local_notifications: ^9.5.3+1
  dwds: ^14.0.1
  image_picker: ^0.8.1+1
  bot_toast: ^4.0.2
  google_maps_flutter_web: ^0.3.0+2
  flutter_typeahead: ^4.0.0
  flutter_google_places: ^0.3.0
  search_map_place:
    git: https://github.com/joshuaplanzapp/search_map_place
  google_maps_place_picker: ^2.0.0-nullsafety.3
  tuple: ^2.0.0
  google_maps_webservice: ^0.0.18
  #firebase: ^7.3.0
  firebase_storage: ^10.2.16
  firebase_database: ^9.0.14
  #easy_contact_picker:
    #git: https://github.com/liuweilyy/easy_contact_picker
  animations: ^2.0.2
  pull_to_refresh: ^2.0.0
  location_permissions: ^4.0.1
  connectivity: ^3.0.6
  location: ^4.3.0
  geolocator: ^7.0.1
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.5
  shared_preferences_web: ^2.0.0
  modal_progress_hud: ^0.1.3
  firebase_core: ^1.3.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  cloud_functions: ^3.2.15
  firebase_analytics: ^9.1.8
  flutter:
    sdk: flutter
  google_maps: ^6.1.0
dependency_overrides:
  args: ^2.1.0
  http: ^0.13.0
  google_maps_flutter: ^2.1.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:

  flutter_launcher_icons: ^0.9.0

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/planzapp_xl.png"
  adaptive_icon_background: "#dfffff"
  adaptive_icon_foreground: "assets/images/planzapp_xl.png"

  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/planzapp_xl.jpg
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
